---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: demoapplocalvolume
  namespace: demoapp
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: demoapplocalvolume
  local:
    path: /data/demoapp
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demoapplocalvolume
  namespace: demoapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: demoapplocalvolume