---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: demoapp
spec:
  selector:
    matchLabels:
      app: demoapp
  replicas: 1
  template:
    metadata:
      labels:
        app: demoapp
        tier: backend
    spec:
      containers:
        - name: backend
          image: gvergne/demo-back
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_HOST
              value: database
            - name: DATABASE_USER
              value: todo
            - name: DATABASE_PASSWORD
              value: todo
            - name: DATABASE_BASE
              value: todo
            - name: HIBERNATE_DLLAUTO
              value: create-drop
          ports:
            - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: demoapp
  labels:
    app: backend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: backend
  type: NodePort
  sessionAffinity: None


---

apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: backend
  namespace: demoapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: demoapp.192.168.64.8.nip.io
      http:
        paths:
          - path: /api/backend
            backend:
              serviceName: backend
              servicePort: 8080