# ------------- BUILD ----------------

FROM node:12-alpine AS build


#RUN npm config set https-proxy https://fr-proxy.groupinfra.com:3128
#RUN npm config set proxy http://fr-proxy.groupinfra.com:3128

RUN npm config set proxy http://10.237.4.220:3128

WORKDIR /build
COPY . .

RUN npm set progress=false && npm config set depth 0 && \
npm install -g @angular/cli && \
npm install && \
npm run build

# ------------- RUN ----------------

FROM nginx:1.15-alpine

COPY default.tmpl /etc/nginx/default.tmpl

RUN rm /usr/share/nginx/html/*

COPY --from=build /build/dist/demo-front/ /usr/share/nginx/html/

ENV NGINX_PORT=81 \
NGINX_SERVER_NAME=localhost \
NGINX_AUTO_INDENT=on

CMD /bin/sh -c "envsubst '\$NGINX_PORT \$NGINX_SERVER_NAME \$NGINX_AUTO_INDENT' < /etc/nginx/default.tmpl > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;' || cat /etc/nginx/conf.d/default.conf"
