server:
  port: ${APPLICATION_PORT:8080}
  servlet:
    contextPath:  ${APPLICATION_CONTEXT:/api/backend}

logging:
  level:
    org.hibernate.SQL: debug

#spring:
#  h2:
#    console:
#      enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#      show-sql: true

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_BASE:todo}
    username: ${DATABASE_USER:todo}
    password: ${DATABASE_PASSWORD:todo}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: ${HIBERNATE_DLLAUTO:create-drop} #create-drop #update #validate

