# ------------- BUILD ----------------

FROM adoptopenjdk/maven-openjdk11 as build

WORKDIR /build

COPY pom.xml .
COPY src/ ./src

RUN mvn \
	-DproxySet=true \
	-DproxyHost=10.237.4.220 \
	-DproxyPort=3128 \
	package

#RUN mvn package

# ------------- RUN ----------------

FROM adoptopenjdk/openjdk11:alpine-jre

EXPOSE 8080

COPY --from=build /build/target/*.jar /app/demo-back.jar

CMD ["java", "-jar", "/app/demo-back.jar"]