# ------------- BUILD ----------------

FROM adoptopenjdk/maven-openjdk11 as build

WORKDIR /build

COPY pom.xml .
COPY src .

#RUN mvn \
#	-Dhttp.proxyHost=fr-proxy.groupinfra.com \
#	-Dhttp.proxyPort=3128 \
#	-Dhttps.proxyHost=fr-proxy.groupinfra.com \
#	-Dhttps.proxyPort=3128 \
#	package

RUN mvn package

# ------------- RUN ----------------

FROM adoptopenjdk/openjdk11:alpine-jre

EXPOSE 8080

COPY --from=build /build/target/*.jar /app/demo-back.jar

CMD ["java", "-jar", "/app/demo-back.jar"]