version: '2'

services:
  
  rpx:
    image: gvergne/demo-rpx
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NGINX_BACKEND_API=http://backend:8080
      - NGINX_FRONTEND_APP=http://frontend:81

  frontend:
    image: gvergne/demo-front
    restart: unless-stopped
    ports:
      - "81"
    depends_on:
      - backend
    links:
      - backend

  backend:
    image: gvergne/demo-back
    restart: unless-stopped
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=todo
      - DATABASE_PASSWORD=todo
      - DATABASE_BASE=todo
      #- HIBERNATE_DLLAUTO=create-drop
      #- HIBERNATE_DLLAUTO=create
      - HIBERNATE_DLLAUTO=update
      #- HIBERNATE_DLLAUTO=create
    depends_on:
      - database
    links:
      - database

  database:
    image: postgres:11.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo
      - POSTGRES_DB=todo
    volumes:
      - /data/db/docker/demo/postgresql:/var/lib/postgresql/data